# üêº Pandas Practice: DataFrames, Selection, Mapping, and More

In [1]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah']
departments = ['Sales', 'Marketing', 'HR', 'Tech']

# Create a DataFrame
df = pd.DataFrame({
    'Name': np.random.choice(names, size=20),
    'Age': np.random.randint(22, 60, size=20),
    'Department': np.random.choice(departments, size=20),
    'Salary': np.random.randint(40000, 120000, size=20),
    'YearsExperience': np.random.randint(0, 20, size=20)
})
df.head()

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

# üß™ PRACTICE QUESTIONS BELOW


# 1Ô∏è‚É£ Use .loc to select all rows where the Department is 'Tech'.
#    - Describe what .loc does and why it's useful for label-based filtering.

In [6]:
df.loc[df['Department'] == 'Tech']
# loc returns all rows that statisfy a certain property or a given label

       Name  Age Department  Salary  YearsExperience
2     Ethan   45       Tech  109479               17
4   Charlie   59       Tech  106557               12
12  Charlie   49       Tech  111211               11
13  Charlie   37       Tech  105697                7
15    Ethan   24       Tech   72606               18
17   Hannah   28       Tech   80397                7
19  Charlie   30       Tech   95591                2


# 2Ô∏è‚É£ Use .iloc to select the first 5 rows and the last two columns.
#    - What is the difference between .loc and .iloc?

In [8]:
print(df.iloc[:5])
df.iloc[-5:]
#retuns rows with a given index or a slice of rows

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

       Name  Age Department  Salary  YearsExperience
15    Ethan   24       Tech   72606               18
16    Diana   58         HR   51534               16
17   Hannah   28       Tech   80397                7
18   Hannah   42      Sales   41016                2
19  Charlie   30       Tech   95591                2


# 3Ô∏è‚É£ Map a new column called 'DeptCode' where:
#     'Sales' -> 1, 'Marketing' -> 2, 'HR' -> 3, 'Tech' -> 4.
#    - Use .map and explain what happens if a value is not mapped.

In [11]:
lookup = {
    'Sales':1,
    'Marketing': 2,
    'HR': 3,
    'Tech': 4
}
df['DeptCode'] = df['Department'].map(lookup)
df.head()
#map applies a function or a dictionary elemnt wise. if the dicitionary, which we used in our case, doesn't map the vlaue its corresponding position is NaN

      Name  Age Department  Salary  YearsExperience  DeptCode
0   George   43         HR   75920               15         3
1    Diana   23  Marketing  107121               12         2
2    Ethan   45       Tech  109479               17         4
3   George   51      Sales   59457               14         1
4  Charlie   59       Tech  106557               12         4


# 4Ô∏è‚É£ Use .apply to calculate a new column 'Seniority' where:
#     - If YearsExperience > 10 ‚Üí 'Senior'
#     - If between 5-10 ‚Üí 'Mid-Level'
#     - Else ‚Üí 'Junior'
#    - Use a lambda function with apply.

In [12]:
def seniority(years: int):
  if years > 10:
    return 'Senior'
  elif years > 5:
    return 'Mid-Level'
  else:
    return 'Junior'

df['Seniority'] = df['YearsExperience'].apply(seniority)
df.head()

      Name  Age Department  Salary  YearsExperience  DeptCode Seniority
0   George   43         HR   75920               15         3    Senior
1    Diana   23  Marketing  107121               12         2    Senior
2    Ethan   45       Tech  109479               17         4    Senior
3   George   51      Sales   59457               14         1    Senior
4  Charlie   59       Tech  106557               12         4    Senior


# 5Ô∏è‚É£ Overwrite all salaries for employees with < 3 years of experience to 35000.
#    - Use boolean indexing with .loc to do this.

In [14]:
df.loc[df['YearsExperience'] < 3, 'Salary'] = 35000


# 6Ô∏è‚É£ Compare using .loc and .iloc to select the same row:
#    - Select the 3rd row using .iloc
#    - Find its index value and use .loc to select the same row by label

In [16]:
print(df.loc[2])
df.iloc[2]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object


# 7Ô∏è‚É£ Check if there are any duplicate names in the dataset.
#    - If there are, show only those duplicated rows.

In [17]:
df[df.duplicated(subset=['Name'], keep=False)]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 8Ô∏è‚É£ Sort the DataFrame by Salary in descending order.
#    - Then sort it by Department and within Department by Age.

In [18]:
df.sort_values(by=['Salary'])

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
11   George   48  Marketing   35000                0         2     Junior
8    George   33      Sales   35000                0         1     Junior
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
16    Diana   58         HR   51534               16         3     Senior
3    George   51      Sales   59457               14         1     Senior
15    Ethan   24       Tech   72606               18         4     Senior
0    George   43         HR   75920               15         3     Senior
14   Hannah   36         HR   77065               10         3  Mid-Level
17   Hannah   28       Tech   80397                7         4  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
7     Ethan   54  Marketing   92995               12         2     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
4   Charlie   59       Tech  106557               12         4     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior


# 9Ô∏è‚É£ Slice the DataFrame to return rows 5 through 12 and columns 'Name', 'Salary'
#    - Try slicing using both label-based and position-based methods.

In [22]:
print(df.loc[5:12, ['Name', 'Salary']])
df.iloc[5:12, [df.columns.get_loc('Name'), df.columns.get_loc('Salary')]]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000
12  Charlie  111211

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000


# üîü Find all rows where the name starts with 'A' or 'D'.
#    - Use string methods with .str accessor.

In [25]:
df.loc[df['Name'].str.startswith(('A', 'D'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior


# 1Ô∏è‚É£1Ô∏è‚É£ Drop all rows where Age is below 25.
#     - Explain whether this modifies the DataFrame in place or returns a copy.

In [31]:
indices = df['Age'] < 25
indices = df[indices].index
df.drop(indices)
#unless we use inplace=True this returns a new dataframe

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 1Ô∏è‚É£2Ô∏è‚É£ Use groupby to calculate the average salary per Department.
#     - Bonus: Show the average age and average experience too.

In [33]:
print(df.groupby('Department')['Salary'].mean())
print('~~~~~~~~~~~~~~~~~~~~')
print(df.groupby('Department')['Age'].mean())
print('~~~~~~~~~~~~~~~~~~~~')
print(df.groupby('Department')['YearsExperience'].mean())

Department
HR           68173.000000
Marketing    86825.000000
Sales        53803.750000
Tech         88706.714286
Name: Salary, dtype: float64
~~~~~~~~~~~~~~~~~~~~
Department
HR           45.666667
Marketing    38.833333
Sales        43.000000
Tech         38.857143
Name: Age, dtype: float64
~~~~~~~~~~~~~~~~~~~~
Department
HR           13.666667
Marketing     8.666667
Sales         6.000000
Tech         10.571429
Name: YearsExperience, dtype: float64


# 1Ô∏è‚É£3Ô∏è‚É£ Use groupby to count how many employees are in each Department.

In [36]:
print(df.groupby('Department').size())

Department
HR           3
Marketing    6
Sales        4
Tech         7
dtype: int64


# 1Ô∏è‚É£4Ô∏è‚É£ Use .apply to normalize the Salary column (min-max scaling between 0 and 1).
#     - Bonus: Write your own normalization function and pass it to apply.

In [39]:
mean = df['Salary'].mean()
std = df['Salary'].std()
def z_score_normalization(series):
    return (series-mean)/std

df['Salary'] = df['Salary'].apply(z_score_normalization)
df.head()

      Name  Age Department    Salary  YearsExperience  DeptCode Seniority
0   George   43         HR -0.071626               15         3    Senior
1    Diana   23  Marketing  0.962257               12         2    Senior
2    Ethan   45       Tech  1.040392               17         4    Senior
3   George   51      Sales -0.617147               14         1    Senior
4  Charlie   59       Tech  0.943568               12         4    Senior


# 1Ô∏è‚É£5Ô∏è‚É£ Use boolean indexing to find all employees who:
#     - Are in 'HR' OR 'Tech', AND have > 5 years of experience.

# üîÅ For many of these tasks, try both .loc and .iloc to build intuition on their differences.

In [44]:
df.loc[(df['Department'].isin(['HR', 'Tech'])) & (df['YearsExperience'] > 5)]

       Name  Age Department    Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR -0.071626               15         3     Senior
2     Ethan   45       Tech  1.040392               17         4     Senior
4   Charlie   59       Tech  0.943568               12         4     Senior
12  Charlie   49       Tech  1.097784               11         4     Senior
13  Charlie   37       Tech  0.915071                7         4  Mid-Level
14   Hannah   36         HR -0.033685               10         3  Mid-Level
15    Ethan   24       Tech -0.181439               18         4     Senior
16    Diana   58         HR -0.879685               16         3     Senior
17   Hannah   28       Tech  0.076725                7         4  Mid-Level